### ISSUE TITLE
Errata not attaching to CentOS 6.10 'os' repository

### ISSUE THREAD

**Issue by pa-jberanek** [nicolas-r/katello-centos-errata-import#9]
I've just installed and configured this tool, pointing at our Katello 3.11 installation.

I populated the config file for 4 repositories:

7.6/os
7.6/updates
6.10/os
6.10/updates

Errata have been applied to all but 6.10/os - is this expected?

```
repositories:
    CentOS-7_6-x86_64-updates:
        pulp_id: ca62213f-77dc-4592-9280-7c59ff6a0e2e
        os_release: 7
    CentOS-7_6-x86_64-os:
        pulp_id: de0f7fd8-4a26-4f7b-a0b5-d57ba2f4cad9
        os_release: 7
    CentOS-6_10-x86_64-updates:
        pulp_id: bbea449c-17af-4710-8461-0b4c27c7777b
        os_release: 6
    CentOS-6_10-x86_64-os:
        pulp_id: 80448054-3cbe-4869-9838-71474a8339c3
        os_release: 6
```
